### PR TITLE
fix link and file scraper bug

### PR DESCRIPTION
**Pull request by Eyobyb**
correct the flow of code in the file.

# Your checklist for this pull request
Thank you for submitting a pull request! To speed up the review process, please follow this checklist:

- [x] My Pull Request is small and focused on one topic so it can be reviewed easily 
- [ ] My code follows the style guidelines of this project (`make format`)
- [x] Commit messages are detailed
- [ ] I have performed a self-review of my code
- [ ] I commented hard-to-understand parts of my code
- [ ] I updated the documentation (docstrings, `/docs`)
- [ ] My changes generate no new warnings (or explain any new warnings and why they're ok)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass when I run `pytest tests` (offline mode)

Additional steps for code with networking dependencies:

- [ ] I followed the [offline and online testing guidelines](https://sherpa-ai.readthedocs.io/en/latest/How_To/Test/test.html#offline-and-online-testing)
- [ ] All tests pass when I run `pytest tests --external_api` (online mode, making network calls)

# Description
This pr fixes the outdated llm model call. so that prompt contractor works 
issue link https://linear.app/aggregate-intellect/issue/SHX-44/fix-file-and-url-prompt-issue

### CODE REVIEW

**Review by saminegash — APPROVED** [review]
LGTM

**Comment by saminegash** [comment]
Can you please make the resolve the conflict

**Comment by oshoma** [comment]
What issue does this fix? Please link to it / mention it in the PR.

**Comment by oshoma** [comment]
1. What issue does this fix? Please link to it / mention it in the PR.
2. Add a test to demonstrate the fix and ensure we don't have a regression in the future

**Review by saminegash — APPROVED** [review]
LGTM

**Pull request merged**
