### PR TITLE
change the expected output of util tests

### PR DESCRIPTION
**Pull request by Eyobyb**
changed the expected output of each testcases.

### CODE REVIEW

**Review by 20001LastOrder — APPROVED** [review]
Nice, I think this fixes two more test cases :)

**Comment by 20001LastOrder** [comment]
Please resolve the merge conflicts and merge

**Comment by oshoma** [comment]
Hi @Eyobyb, I just tried merging your branch into main and got merge conflicts. 

I didn't realize you were working on this. I actually made similar changes today, plus a little more. https://github.com/Aggregate-Intellect/sherpa/pull/254

How about you review #254 for me and we close this one (#234) since 254 is a superset?

**Comment by oshoma** [comment]
Closing, since we merged #254, which is a superset of this PR.

**Pull request closed without merging**
