### PR TITLE
create verbose logger template

### PR DESCRIPTION
**Pull request by 20001LastOrder**
Create the template for the verbose logger continuously updating the user with execution status.

### CODE REVIEW

**Comment by 20001LastOrder** [comment]
@johnnykfeng Please check this PR as well.

**Comment by johnnykfeng** [comment]
@20001LastOrder It looks good. I assume you have tested this and it works?

**Comment by 20001LastOrder** [comment]
> @20001LastOrder It looks good. I assume you have tested this and it works?

Yes, it will print _Sherpa is thinking_ at the beginning of the execution

**Comment by amirfz** [comment]
should i merge this?

**Comment by johnnykfeng** [comment]
> should i merge this?

To me it looks fine, so yes

**Review by amirfz — APPROVED** [review]

**Pull request merged**
