### PR TITLE
Fix bandit warnings

### PR DESCRIPTION
**Pull request by oshoma**
# Your checklist for this pull request
Thank you for submitting a pull request! To speed up the review process, please follow this checklist:

- [x] My Pull Request is small and focused on one topic so it can be reviewed easily 
- [x] My code follows the style guidelines of this project (`make format`)
- [x] Commit messages are detailed
- [x] I have performed a self-review of my code
- [ ] I commented hard-to-understand parts of my code
- [ ] I updated the documentation (docstrings, `/docs`)
- [x] My changes generate no new warnings (or explain any new warnings and why they're ok)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass when I run `pytest tests` (offline mode)

Additional steps for code with networking dependencies:

- [ ] I followed the [offline and online testing guidelines](https://sherpa-ai.readthedocs.io/en/latest/How_To/Test/test.html#offline-and-online-testing)
- [ ] All tests pass when I run `pytest tests --external_api` (online mode, making network calls)

# Description
Add Bandit to provide security checks in `make lint` and address Bandit security warnings.

This change improves the security of our code.

Depends on #343 .

### CODE REVIEW

**Comment by oshoma** [comment]
let's hold off on this PR for now, I will rebase atop `main` after a few others are merged in

**Comment by oshoma** [comment]
I rebased this branch atop main and ran into a test failure:

```
tests/integration_tests/test_orchestrator.py:75: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
sherpa_ai/orchestrator.py:54: in execute
    agent.run()
sherpa_ai/agents/base.py:92: in run
    action_output = self.act(action, inputs)
sherpa_ai/agents/base.py:141: in act
    return action.execute(**inputs)
sherpa_ai/actions/arxiv_search.py:38: in execute
    result = self.search_tool._run(query)
sherpa_ai/tools.py:58: in _run
    data = requests.get(url, timeout=HTTP_GET_TIMEOUT)
```

This is happening because I added a timeout in tools.py to make it safe to run in production, and this test is doing an actual HTTP GET which happened to run slowly just now and trigger the timeout. 

The solution here is to mock the call to `requests.get()` in ArxivSearch._run at sherpa_ai/tools.py:58. We should not be using the network in our tests.

**Comment by oshoma** [comment]
I re-ran the test job and it succeeded. So this is an intermittent error, we should expect it to reoccur sometimes when github tests run slowly. This will keep happening until we fix the test to use a mock. I will create a github issue to address this.

@20001LastOrder please proceed on reviewing this PR. I have rebased it on main and it no longer depends on #343 .

**Comment by 20001LastOrder** [comment]
This PR seems to have many duplicated changes as #343, @oshoma How should we proceed with merging them?

**Comment by oshoma** [comment]
Closing this. I have created a new PR https://github.com/oshoma/sherpa/pull/1 for this work and will submit it to the Sherpa repo after #356 is merged.

**Pull request closed without merging**
