### PR TITLE
addressing #395

### PR DESCRIPTION
**Pull request by amirfz**
# Description
addressing the demo issue documented in #395 . essentially replacing the existing document search demo with an up to date version consistent with tutorials

# Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Maintenance
- [ ] New release

# Related issues
#395 

# Checklists
To speed up the review process, please follow these checklists:

## Development
- [x] The Pull Request is small and focused on one topic
- [ ] Lint rules pass locally (`make format && make lint`)
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development (`make test`)
- [ ] The changes generate no new warnings (or explain any new warnings and why they're ok)
- [ ] Commit messages are detailed
- [ ] Changed code is self-explanatory and/or I added comments
- [ ] I updated the documentation (docstrings, /docs)
See the testing guidelines for help on tests, especially those involving web services.

## Code review
- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached.
- [ ] I have performed a self-review of my code
- [ ] Issue from task tracker has a link to this pull request

💔 Thank you for submitting a pull request!

### CODE REVIEW

**Comment by 20001LastOrder** [comment]
It seems to contain quite some unnecessary files. I will need to clean it up a bit

**Comment by amirfz** [comment]
ok if it is not a quick thing then either assign it to someone else or
let's come back to it later

**Comment by amirfz** [comment]
@20001LastOrder removed the extra files from this PR. please take a look

**Review by 20001LastOrder — APPROVED** [review]
Looks good

**Pull request merged**
